pipeline-name: AutocalibrationPipeline
model-version: 1
results-path: /gpfs/gpfs_gl4_16mb/b9p111/fdl_sw/experiments_results
min_alpha: 0.01
log-minimal: True
batch-size-train: 64
batch-size-test: 256
save-interval: 100
log-interval: 10
wavelengths:
  - "0094"
  - "0131"
  - "0171"
  - "0193"
  - "0211"
  - "0304"
  - "0335"
instruments:
  - AIA
  - AIA
  - AIA
  - AIA
  - AIA
  - AIA
  - AIA
actual-resolution: 512
subsample: 4
yr-range:
  - 2012
  - 2013
