# This file contains all the inputs necessary to reproduce the results published at Dos Santos et al. 2021 (https://arxiv.org/abs/2012.14023).
# Update the paths to your local dataset. A description and default values of each input here can be fund at /src/sdo/parse_arg.py.
# Any change in any of these parameters may not produce the same results of the reference paper.

actual-resolution: 512
add-metrics-interval: 100
apodize: true
autocal-flip-image: true
autocal-max-alpha: 1.0
autocal-min-alpha: 0.01
autocal-noise-image: false
autocal-sigmoid-scale: 1.0
autocal-threshold-black: false
autocal-threshold-black-value: 0.09
autocal-tolerance: 0.05
batch-size-test: 256
batch-size-train: 64
config: autocal_paper_config.yaml
continue-training: false
data-basedir: /fdl_sdo_data/SDOMLmm/fdl_sw/SDOMLmm
data-inventory: /fdl_sdo_data/bucket/inventory.pkl
dataloader-workers: 14
day-step: 1
deterministic-cuda: true
experiment-name: luiz_exp_36_apodize
h-step: 6
instruments:
- AIA
- AIA
- AIA
- AIA
- AIA
- AIA
- AIA
log-interval: 10
log-minimal: true
min-step: 60
mnt-step: 1
model-version: 6
num-epochs: 1000
optimizer-lr: 0.001
optimizer-weight-decay: 0
pipeline-name: AutocalibrationPipeline
random-seed: 1
results-path: /fdl_sdo_data/bucket/EXPERIMENT_RESULTS/AUTOCAL/luiz_exp_36_apodize
save-interval: 100
saved-model-path: null
saved-optimizer-path: null
scaling: true
start-epoch-at: 1
subsample: 2
test-ratio: 0.3
wavelengths:
- '0094'
- '0131'
- '0171'
- '0193'
- '0211'
- '0304'
- '0335'
yr-range:
- 2010
- 2013
